# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-06 17:24
from __future__ import unicode_literals

from django.db import migrations
import django_markdown.models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20160511_1105'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='body',
            field=django_markdown.models.MarkdownField(),
        ),
    ]
